name: Restrict Main Branch Merge

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from dev branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
            echo "❌ Error: Only pull requests from 'dev' branch can be merged into 'main'."
            exit 1
          fi
